name: modular_login
description: A Modular Login Screen

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^0.13.4+2
  firebase_auth: ^0.15.5+2
  google_sign_in: ^4.1.4
  http: ^0.12.0+4
  webfeed: ^0.4.2
  url_launcher: ^5.2.5
  flutter_webview_plugin: ^0.3.10+1
  toast: ^0.1.5
  intl: ^0.15.8
  shared_preferences: ^0.5.6+3
  carousel_slider: ^1.3.0
  youtube_player_flutter: ^6.1.0+4

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/icon.png
    - assets/google_logo.png
    - assets/coronaVirus.gif
    - assets/photoNotAvailaible.png
    - assets/worldIcon.png
    - assets/indiaFlag.png
    - assets/washed_away_covid-19.gif
    - assets/howItSpreads.png
    - assets/prevention.png
    - assets/symptoms.png
    - assets/mythImg/myth1.png
    - assets/mythImg/myth2.png
    - assets/mythImg/myth3.png
    - assets/mythImg/myth4.png
    - assets/mythImg/myth5.png
    - assets/mythImg/myth6.png
    - assets/mythImg/myth7.png
    - assets/mythImg/myth8.png
    - assets/mythImg/myth9.png
    - assets/mythImg/myth10.png
    - assets/mythImg/myth11.png
    - assets/mythImg/myth12.png
    - assets/mythImg/myth13.png
    - assets/mythImg/myth14.png
    - assets/who.png
    - assets/worldStatsIcon.png
  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages